# -*- coding: utf-8 -*-
"""blip_task_ocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j1jDDT9ZrrgynlSb2SZVhPUnyzEQd6c
"""

# !pip install flask flask-cors requests pdfplumber pytesseract pdf2image beautifulsoup4 boto3 pyngrok anthropic

import os
import re
import io
import json
import tempfile
import datetime
import warnings
import threading

import requests
import pdfplumber
import pytesseract
from pdf2image import convert_from_path, convert_from_bytes
from bs4 import BeautifulSoup

from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok

warnings.filterwarnings("ignore")

app = Flask(__name__)
CORS(app)
app.config["MAX_CONTENT_LENGTH"] = 50 * 1024 * 1024  # 50 MB cap

os.environ["NGROK_AUTH_TOKEN"] = "3365NptIuQXwEr8DryJhrQbVNe8_7eBQ6XLZFzcoyzRybeude"

CONFIG = {
    "ocr_dpi": 400,
    "use_llm_default": False,
    "llm_model": os.getenv("LLM_MODEL", "claude-sonnet-4-6"),
}

# extraction schema (the "required data")
SCHEMA = {
    # --- identity ---
    "model": {"type": "str", "aliases": ["model", "model name", "cell type", "part number", "part no", "type"]},
    "manufacturer": {"type": "str", "aliases": ["manufacturer", "made by", "supplier", "brand"]},
    "manufacture_date": {"type": "str", "aliases": ["manufacture date", "production date", "date of manufacture", "mfg date", "manufacturing date"]},
    "chemistry": {"type": "str", "aliases": ["chemistry", "cathode", "cell chemistry", "material"]},

    # --- capacity / energy ---
    "nominal_capacity_Ah": {"type": "num", "aliases": ["nominal capacity", "rated capacity", "typical capacity", "capacity"]},
    "min_capacity_Ah": {"type": "num", "aliases": ["min. capacity", "min capacity", "minimum capacity"]},
    "nominal_energy_Wh": {"type": "num", "aliases": ["nominal energy", "rated energy", "typical energy", "energy"]},
    "min_energy_Wh": {"type": "num", "aliases": ["min. energy", "min energy", "minimum energy"]},
    "initial_ir_mOhm": {"type": "num", "aliases": ["initial ir", "initial internal resistance", "initial resistance", "internal resistance", "ir", "ac internal resistance", "ac impedance"]},

    # --- voltage ---
    "nominal_voltage_V": {"type": "num", "aliases": ["nominal voltage", "rated voltage", "typical voltage", "working voltage"]},
    "charge_cutoff_voltage_V": {"type": "num", "aliases": ["charging cut-off voltage", "charge cut-off voltage", "charge cutoff voltage", "charging cutoff voltage", "end of charge voltage", "end-of-charge voltage"]},
    "discharge_cutoff_voltage_V": {"type": "num", "aliases": ["discharging cut-off voltage", "discharge cut-off voltage", "discharge cutoff voltage", "discharging cutoff voltage", "end of discharge voltage", "end-of-discharge voltage"]},
    "standard_charging_voltage_V": {"type": "num", "aliases": ["standard charging voltage", "standard charge voltage"]},
    "absolute_charging_voltage_V": {"type": "num", "aliases": ["absolute charging voltage", "absolute charge voltage", "max charging voltage limit"]},
    "charging_voltage_V": {"type": "num", "aliases": ["charging voltage", "charge voltage"]},

    # --- current (NEW) ---
    "max_charge_current_A": {"type": "num", "aliases": ["max charge current", "maximum charge current", "max charging current", "maximum charging current", "standard charge current", "continuous charge current"]},
    "max_discharge_current_A": {"type": "num", "aliases": ["max discharge current", "maximum discharge current", "max discharging current", "maximum discharging current", "standard discharge current", "continuous discharge current"]},

    # --- power ---
    "standard_charging_power_W": {"type": "num", "aliases": ["standard charging power", "standard charge power"]},
    "standard_discharging_power_W": {"type": "num", "aliases": ["standard discharging power", "standard discharge power"]},

    # --- temperature ---
    "absolute_charging_temp_C": {"type": "str", "aliases": ["absolute charging temperature (battery temperature)", "absolute charging temperature", "absolute charge temperature", "absolute charging temp (battery temp)", "absolute charging temp", "absolute charge temp"]},
    "absolute_discharging_temp_C": {"type": "str", "aliases": ["absolute discharging temperature (battery temperature)", "absolute discharging temperature", "absolute discharge temperature", "absolute discharging temp (battery temp)", "absolute discharging temp", "absolute discharge temp"]},
    "charging_temperature_C": {"type": "str", "aliases": ["charging temperature", "charge temperature", "charging temp", "charge temp"]},
    "discharging_temperature_C": {"type": "str", "aliases": ["discharging temperature", "discharge temperature", "discharging temp", "discharge temp"]},
    "storage_temperature_C": {"type": "str", "aliases": ["storage temperature", "storage temp"]},
    "operating_temp_C": {"type": "str", "aliases": ["operating temperature", "operating temp", "working temperature", "operation temperature", "ambient temperature"]},  # NEW
    "max_operating_temp_C": {"type": "num", "aliases": ["maximum operating temperature", "max operating temperature", "maximum operating temp", "max operating temp"]},
    "min_operating_temp_C": {"type": "num", "aliases": ["minimum operating temperature", "min operating temperature", "minimum operating temp", "min operating temp"]},
    "max_safe_temp_C": {"type": "num", "aliases": ["maximum safe temperature", "max safe temperature", "maximum safe temp", "max safe temp"]},
    "min_safe_temp_C": {"type": "num", "aliases": ["minimum safe temperature", "min safe temperature", "minimum safe temp", "min safe temp"]},

    # --- physical ---
    "weight_g": {"type": "num", "aliases": ["weight", "cell weight", "mass", "net weight"]},  # NEW
    "dimensions_mm": {"type": "str", "aliases": ["dimensions", "dimension", "cell dimensions", "size (l*w*h)", "size", "l*w*h", "outline dimension"]},  # NEW
    "height_with_terminal_mm": {"type": "num", "aliases": ["height(h) with terminal", "height with terminal", "height (h) with terminal", "height", "cell height"]},
    "length_mm": {"type": "num", "aliases": ["length", "length(l)", "length (l)", "cell length", "width"]},
    "thickness_mm": {"type": "num", "aliases": ["thickness", "thickness(t)", "thickness (t)", "cell thickness", "depth"]},
    "laser_welding_depth_mm": {"type": "num", "aliases": ["laser welding depth", "welding depth"]},

    # --- cycle life ---
    "cycle_life": {"type": "int", "aliases": ["cycle life", "rated cycle life", "cycle count", "service life"]},  # NEW (replaces rated_cycle_life)
    "cycle_25C_standard": {"type": "str", "aliases": ["25℃ standard cycle", "25c standard cycle", "standard cycle"]},
    "cycle": {"type": "str", "aliases": ["cycle"]},
    "storage": {"type": "str", "aliases": ["storage"]},
}

FIELDS = list(SCHEMA.keys())
MISSING = None  # value used when a field is not found


def empty_spec():
    return {k: MISSING for k in FIELDS}

# text acquisition (file / pdf-bytes / html), OCR fallback
# ==========================================================================
def is_url(s):
    return s.lower().startswith(("http://", "https://"))


def acquire_text(source):
    """Return (text, table_pairs, kind) for a local path or URL.

    table_pairs: list of (label, value) tuples from any 2-column table rows.
    kind: 'pdf_file' | 'pdf_url' | 'html_url'
    """
    if not is_url(source):
        text, pairs = text_from_pdf_path(source)
        return text, pairs, "pdf_file"

    headers = {"User-Agent": "Mozilla/5.0 (datasheet-extractor)"}
    resp = requests.get(source, headers=headers, timeout=30)
    resp.raise_for_status()
    ctype = resp.headers.get("Content-Type", "").lower()

    is_pdf = (
        "application/pdf" in ctype
        or source.lower().split("?")[0].endswith(".pdf")
        or resp.content[:5] == b"%PDF-"
    )
    if is_pdf:
        text, pairs = text_from_pdf_bytes(resp.content)
        return text, pairs, "pdf_url"
    text, pairs = text_from_html(resp.text)
    return text, pairs, "html_url"


def _value_score(cell):
    """Heuristic: how much a cell looks like a spec VALUE (vs a label/remark).
    Higher = more value-like. Short cells with a number+unit score highest;
    long prose scores low/negative. Ranges (-20~60) score high too."""
    s = str(cell).strip()
    if not s:
        return -100
    words = len(s.split())
    score = 0
    if re.search(r"\d", s):
        score += 2
    if re.search(r"\d\s*(?:v|ah|wh|mω|mohm|w|mm|℃|°c|kg|g|n|nm|a)\b", s.lower()):
        score += 3
    # a range like -20~60 or -20℃~60℃ is a strong value signal
    if re.search(r"-?\d.*(?:~|to|\u2013|\u2014).*-?\d", s):
        score += 3
    score -= max(0, words - 3)        # penalize prose
    if words > 6:
        score -= 5
    return score


def _pairs_from_pdf(pdf):
    """Extract (label, value) pairs from 2+ column tables in a pdfplumber pdf.

    For rows with 3+ columns (e.g. Item | Standard | Remarks), choose the
    column that looks most like a value, not blindly the last one. Also emit
    every other candidate as a fallback so coercion can pick a valid one.
    """
    pairs = []
    for page in pdf.pages:
        for table in page.extract_tables() or []:
            for row in table:
                cells = [str(c).strip() for c in row if c and str(c).strip()]
                if len(cells) < 2:
                    continue
                label = cells[0]
                candidates = cells[1:]
                best = max(candidates, key=_value_score)
                pairs.append((label, best))
                for c in candidates:
                    if c != best:
                        pairs.append((label, c))
    return pairs


def text_from_pdf_path(path):
    pages = []
    with pdfplumber.open(path) as pdf:
        pairs = _pairs_from_pdf(pdf)
        for i, page in enumerate(pdf.pages):
            txt = page.extract_text() or ""
            if len(txt.strip()) >= 40:
                pages.append(txt)
            else:
                imgs = convert_from_path(path, dpi=CONFIG["ocr_dpi"],
                                         first_page=i + 1, last_page=i + 1)
                pages.append(ocr_image(imgs[0]) if imgs else "")
    return "\n".join(pages), pairs


def text_from_pdf_bytes(data):
    pages = []
    ocr_pages = []
    with pdfplumber.open(io.BytesIO(data)) as pdf:
        pairs = _pairs_from_pdf(pdf)
        for i, page in enumerate(pdf.pages):
            txt = page.extract_text() or ""
            if len(txt.strip()) >= 40:
                pages.append(txt)
            else:
                pages.append(None)
                ocr_pages.append(i + 1)
    for pageno in ocr_pages:
        imgs = convert_from_bytes(data, dpi=CONFIG["ocr_dpi"],
                                  first_page=pageno, last_page=pageno)
        pages[pageno - 1] = ocr_image(imgs[0]) if imgs else ""
    return "\n".join(p or "" for p in pages), pairs


def text_from_html(html):
    soup = BeautifulSoup(html, "html.parser")
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()
    pairs = []
    lines = []
    for table in soup.find_all("table"):
        for tr in table.find_all("tr"):
            cells = [c.get_text(" ", strip=True) for c in tr.find_all(["td", "th"])]
            cells = [c for c in cells if c]
            if len(cells) >= 2:
                # pick the most value-like cell, not blindly the last
                best = max(cells[1:], key=_value_score)
                pairs.append((cells[0], best))
                for c in cells[1:]:
                    if c != best:
                        pairs.append((cells[0], c))
            if cells:
                lines.append(" : ".join(cells))
    text = soup.get_text("\n", strip=True) + "\n" + "\n".join(lines)
    return text, pairs


def ocr_image(pil_image):
    img = pil_image.convert("L")
    best = ""
    for psm in (4, 6, 11):
        out = pytesseract.image_to_string(img, config=f"--oem 3 --psm {psm}")
        if len(out.strip()) > len(best.strip()):
            best = out
    return best

# regex extractor (offline baseline)
# ==========================================================================
_NUM = r"[-+]?\d+(?:[.,]\d+)?"


def _looks_like_range(s):
    """True for things like '-20~60', '-20C to 60C' that should stay strings."""
    return bool(re.search(r"-?\d.*(?:~|to|\u2013|\u2014).*\d", s))


def _looks_like_dimensions(s):
    """True for 'L*W*H' style dimension strings: '174*72*207' or '174x72x207'."""
    return bool(re.search(r"\d+(?:[.,]\d+)?\s*[x*×]\s*\d+(?:[.,]\d+)?\s*[x*×]\s*\d+", s.lower()))


# Per-field-suffix sanity bounds, used to reject values that matched a label
# but are clearly the wrong number (e.g. a C-rate, a percentage, stray text).
_BOUNDS = {
    "_V": (0.3, 6.0),          # single-cell voltage
    "_Ah": (1.0, 2000.0),
    "_Wh": (1.0, 20000.0),
    "_mOhm": (0.01, 50.0),     # cell internal resistance in milliohm
    "_A": (0.1, 2000.0),       # charge/discharge current
    "_W": (10.0, 100000.0),    # power; floor raised so stray '1' is rejected
    "_g": (50.0, 50000.0),     # cell mass in grams
    "_mm": (0.5, 1000.0),
    "_C": (-60.0, 150.0),      # a temperature
}


def _bounds_for(key):
    # longest suffix wins (so _mOhm beats shorter suffixes, etc.)
    for suffix in sorted(_BOUNDS, key=len, reverse=True):
        if key.endswith(suffix):
            return _BOUNDS[suffix]
    return None


def _is_junk_value(raw, key=None):
    """Reject values that are obviously not a spec value."""
    low = raw.lower().strip()
    if not low:
        return True
    if len(low.split()) > 6:
        return True
    is_temp = bool(key) and key.endswith("_C")
    # P-rate always junk (e.g. '0.5p')
    if re.match(r"^\d+(?:[.,]\d+)?\s*p\b", low):
        return True
    # C-rate like '0.5c' / '1c' — but NOT a Celsius temperature. Skip for _C.
    if not is_temp:
        if re.match(r"^\d+(?:[.,]\d+)?c\b", low) and "°" not in raw and "℃" not in raw:
            return True
    # bare percentage
    if re.match(r"^\d+(?:[.,]\d+)?\s*%$", low):
        return True
    return False


def _coerce_value(key, raw_value):
    """Coerce + VALIDATE a raw value for a given field key.
    Returns the typed value, or None if the value is junk / out of range."""
    ftype = SCHEMA[key]["type"]
    raw_value = str(raw_value).strip(" :\t|").strip()
    if not raw_value or _is_junk_value(raw_value, key):
        return None

    # dimensions field: keep the L*W*H string verbatim
    if key == "dimensions_mm":
        if _looks_like_dimensions(raw_value):
            return re.sub(r"\s+", "", raw_value)[:60]
        return None

    # Range strings stay as text (temperatures, etc.), only for str / _C fields.
    if _looks_like_range(raw_value):
        if ftype == "str" or key.endswith("_C"):
            return re.sub(r"\s+", " ", raw_value)[:80]
        return None

    if ftype in ("num", "int"):
        m = re.search(_NUM, raw_value)
        if not m:
            return None
        try:
            n = float(m.group(0).replace(",", "."))
        except ValueError:
            return None
        rng = _bounds_for(key)
        if rng and not (rng[0] <= n <= rng[1]):
            return None
        return int(round(n)) if ftype == "int" else n

    # string field: keep short, single-value-ish strings only
    cleaned = re.sub(r"\s+", " ", raw_value).strip()
    if not cleaned:
        return None
    if key in ("model", "manufacturer") and len(cleaned) < 2:
        return None
    return cleaned[:80]


def _build_alias_index():
    """Map each alias -> field key, longest alias first so specific labels win
    (e.g. 'absolute charging voltage' before 'charging voltage')."""
    pairs = []
    for key, spec in SCHEMA.items():
        for alias in spec["aliases"]:
            pairs.append((alias.lower(), key))
    pairs.sort(key=lambda p: len(p[0]), reverse=True)
    return pairs


_ALIAS_INDEX = _build_alias_index()


def _split_explicit(line):
    """If the line has an explicit separator, return (label, value) else None."""
    for sep in (" : ", "\t", " = "):
        if sep in line:
            left, right = line.split(sep, 1)
            if left.strip() and right.strip():
                return left.strip(), right.strip()
    if ":" in line:
        left, right = line.split(":", 1)
        if left.strip() and right.strip() and not left.strip()[-1].isdigit():
            return left.strip(), right.strip()
    return None


def _alias_matches(llabel, alias):
    """Generic, short aliases (<=7 chars or single word) must match the label
    EXACTLY, to avoid stealing from longer labels. Longer aliases may match by
    startswith/contains."""
    if llabel == alias:
        return True
    if len(alias) <= 7 or " " not in alias:
        return False
    return llabel.startswith(alias) or alias in llabel


def extract_from_pairs(pairs, spec, matches):
    """Assign values from clean (label, value) pairs (e.g. PDF table cells)."""
    for label, value in pairs:
        if label is None or value is None:
            continue
        llabel = str(label).strip().lower()
        sval = str(value).strip()
        if not llabel or not sval:
            continue
        for alias, key in _ALIAS_INDEX:
            if spec.get(key) is not None:
                continue
            if _alias_matches(llabel, alias):
                coerced = _coerce_value(key, sval)
                if coerced is not None:
                    spec[key] = coerced
                    matches[key] = f"{str(label).strip()[:40]} => {sval[:40]}"
                break
    return spec, matches


def extract_from_text(text, spec, matches):
    """Alias-anchored scan over free text lines."""
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue

        ex = _split_explicit(line)
        if ex:
            extract_from_pairs([ex], spec, matches)
            continue

        lline = line.lower()
        for alias, key in _ALIAS_INDEX:
            if spec.get(key) is not None:
                continue
            if len(alias) <= 7 or " " not in alias:
                continue
            if lline.startswith(alias):
                remainder = line[len(alias):].strip(" :=\t-")
                coerced = _coerce_value(key, remainder)
                if coerced is not None:
                    spec[key] = coerced
                    matches[key] = f"{alias} => {remainder[:40]}"
                break
    return spec, matches


def extract_regex(text, table_pairs=None):
    """Generic label->value extractor over the full SCHEMA."""
    spec = empty_spec()
    matches = {}

    if table_pairs:
        extract_from_pairs(table_pairs, spec, matches)
    extract_from_text(text, spec, matches)

    low = text.lower()

    # chemistry fallback by content pattern
    if spec.get("chemistry") is None:
        m = re.search(r"(lifepo4|lfp|li-?ion lifepo4|nmc|nca|lco|lto|lithium iron phosphate)", low)
        if m:
            spec["chemistry"] = m.group(1)
    if isinstance(spec.get("chemistry"), str):
        c = spec["chemistry"].lower()
        norm = ("LFP" if ("lifepo4" in c or "lfp" in c or "iron phosphate" in c)
                else "NMC" if "nmc" in c else "NCA" if "nca" in c
                else "LCO" if "lco" in c else "LTO" if "lto" in c
                else spec["chemistry"].upper())
        spec["chemistry"] = norm

    # manufacturer fallback
    if spec.get("manufacturer") is None:
        m = re.search(r"\b(eve|catl|calb|byd|samsung sdi|lg energy|lg chem|panasonic|gotion|lishen)\b", low)
        if m:
            spec["manufacturer"] = m.group(1).upper()

    # capacity / energy fallbacks
    if spec.get("nominal_capacity_Ah") is None:
        if spec.get("min_capacity_Ah") is not None:
            spec["nominal_capacity_Ah"] = spec["min_capacity_Ah"]
        else:
            m = re.search(r"(\d{2,4}(?:[.,]\d+)?)\s*ah\b", low)
            if m:
                v = _coerce_value("nominal_capacity_Ah", m.group(0))
                if v is not None:
                    spec["nominal_capacity_Ah"] = v
    if spec.get("nominal_energy_Wh") is None and spec.get("min_energy_Wh") is not None:
        spec["nominal_energy_Wh"] = spec["min_energy_Wh"]

    # dimensions fallback: look for an L*W*H pattern anywhere
    if spec.get("dimensions_mm") is None:
        m = re.search(r"\d+(?:[.,]\d+)?\s*[x*×]\s*\d+(?:[.,]\d+)?\s*[x*×]\s*\d+(?:[.,]\d+)?", text)
        if m:
            v = _coerce_value("dimensions_mm", m.group(0))
            if v is not None:
                spec["dimensions_mm"] = v

    # operating_temp_C fallback: derive from a min/max pair if available
    if spec.get("operating_temp_C") is None:
        lo, hi = spec.get("min_operating_temp_C"), spec.get("max_operating_temp_C")
        if lo is not None and hi is not None:
            spec["operating_temp_C"] = f"{lo}℃ ~ {hi}℃"

    return spec, matches

# LLM extractor (optional, Anthropic API)
# ==========================================================================
LLM_SYSTEM = (
    "You extract battery/cell datasheet parameters. "
    "Return ONLY a JSON object, no prose, no markdown fences. "
    "Use null for anything not present. Convert units to the schema "
    "(capacity Ah, energy Wh, internal resistance milliohm, currents A, weight g). "
    "Do not invent values."
)


def extract_llm(text, model):
    """Use the Anthropic API. Requires ANTHROPIC_API_KEY and the anthropic SDK."""
    import anthropic
    client = anthropic.Anthropic()
    prompt = (
        "Extract these fields from the datasheet text below.\n"
        f"Return exactly this JSON shape (keys fixed):\n{json.dumps(empty_spec(), indent=2)}\n\n"
        "- dimensions_mm: string like '207.5*173.7*72'\n"
        "- operating_temp_C: string range like '-20℃ ~ 60℃'\n"
        "- cycle_life: integer\n"
        "- weight_g: grams (number)\n"
        "- max_charge_current_A / max_discharge_current_A: amperes (number)\n"
        "- If multiple values exist, pick the nominal single-cell value.\n\n"
        f"DATASHEET TEXT:\n{text[:18000]}"
    )
    msg = client.messages.create(
        model=model, max_tokens=1024, system=LLM_SYSTEM,
        messages=[{"role": "user", "content": prompt}],
    )
    raw = "".join(b.text for b in msg.content if getattr(b, "type", "") == "text")
    raw = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    data = json.loads(raw)

    spec = empty_spec()
    for k in FIELDS:
        if k in data and data[k] is not None:
            spec[k] = data[k]
    return spec


def merge_specs(primary, secondary):
    """Fill primary's None fields from secondary."""
    out = dict(primary)
    for k in FIELDS:
        if out.get(k) is None and secondary.get(k) is not None:
            out[k] = secondary[k]
    return out

# core extraction (used by both endpoints)
# ==========================================================================
def run_extraction(source, use_llm=False, llm_model=None):
    """Acquire text and extract specs. Returns a result dict."""
    llm_model = llm_model or CONFIG["llm_model"]
    text, table_pairs, kind = acquire_text(source)

    spec, matches = extract_regex(text, table_pairs)   # deterministic baseline
    method = "regex"
    llm_error = None

    if use_llm:
        try:
            llm_spec = extract_llm(text, llm_model)
            spec = merge_specs(llm_spec, spec)  # prefer LLM, backfill from regex
            method = "llm+regex"
        except Exception as e:
            llm_error = str(e)
            method = "regex (llm failed)"

    found = sum(1 for k in FIELDS if spec.get(k) is not None)
    result = {
        "specs": spec,
        "fields_found": found,
        "fields_total": len(FIELDS),
        "input_kind": kind,
        "method": method,
    }
    if llm_error:
        result["llm_error"] = llm_error
    return result


# ==========================================================================
# response formatting
# ==========================================================================
def format_response(source, result):
    """Build the {success: ...} response envelope."""
    resp = {
        "success": True,
        "source": source,
        "timestamp": datetime.datetime.now().isoformat(),
        "fields_found": result["fields_found"],
        "input_kind": result["input_kind"],
        "specs": result["specs"],
    }
    if result.get("llm_error"):
        resp["llm_error"] = result["llm_error"]
    return resp


# ==========================================================================
# Flask app + endpoints
# ==========================================================================
def _truthy(v):
    return str(v).strip().lower() in ("1", "true", "yes", "on")


@app.route("/health-ocr", methods=["GET"])
def health_datasheet():
    try:
        return jsonify({
            "status": "running",
            "timestamp": datetime.datetime.now().isoformat(),
            "task": "ocr task",
        }), 200
    except Exception as e:
        return jsonify({"status": "unhealthy", "error": str(e)}), 500
    # try:
    #     tess_ok = True
    #     try:
    #         pytesseract.get_tesseract_version()
    #     except Exception:
    #         tess_ok = False
    #     llm_ok = bool(os.getenv("ANTHROPIC_API_KEY"))
    #     return jsonify({
    #         "success": True,
    #         "status": "running",
    #         "service": "Battery Datasheet Extraction",
    #         "timestamp": datetime.datetime.now().isoformat(),
    #         "components": {
    #             "tesseract_available": tess_ok,
    #             "llm_available": llm_ok,
    #         },
    #     }), 200
    # except Exception as e:
    #     return jsonify({
    #         "success": False, "status": "unhealthy",
    #         "error": str(e),
    #         "timestamp": datetime.datetime.now().isoformat(),
    #     }), 500


@app.route("/datasheet-extract", methods=["POST"])
def datasheet_extract():
    """Extract specs from an uploaded datasheet PDF (multipart/form-data)."""
    tmp_path = None
    try:
        if "file" not in request.files:
            return jsonify({
                "success": False,
                "error": "No file uploaded. Expected 'file' parameter with a PDF datasheet",
            }), 400

        file = request.files["file"]
        if not file.filename:
            return jsonify({"success": False, "error": "Empty filename"}), 400
        if not file.filename.lower().endswith(".pdf"):
            return jsonify({
                "success": False,
                "error": "File must be PDF format (.pdf extension)",
            }), 400

        use_llm = _truthy(request.form.get("llm", CONFIG["use_llm_default"]))

        print(f"\n[ENDPOINT] /datasheet-extract called")
        print(f"[ENDPOINT] File: {file.filename} | llm: {use_llm}")

        tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
        tmp_path = tmp.name
        file.save(tmp_path)
        tmp.close()

        result = run_extraction(tmp_path, use_llm=use_llm)
        print(f"[ENDPOINT] Extracted {result['fields_found']}/{result['fields_total']} fields")

        response = format_response(file.filename, result)
        print(f"[ENDPOINT] Processing complete")
        return jsonify(response), 200

    except Exception as e:
        print(f"[ENDPOINT ERROR] {str(e)}")
        return jsonify({
            "success": False, "error": str(e),
            "timestamp": datetime.datetime.now().isoformat(),
        }), 500
    finally:
        if tmp_path:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass


@app.route("/datasheet-extract-url", methods=["POST"])
def datasheet_extract_url():
    """Extract specs from a URL (PDF link OR HTML product page). JSON body."""
    try:
        data = request.get_json(silent=True) or {}
        url = (data.get("url") or "").strip()

        if not url:
            return jsonify({"success": False, "error": "Missing 'url' in request body"}), 400
        if not is_url(url):
            return jsonify({"success": False, "error": "'url' must start with http:// or https://"}), 400

        use_llm = _truthy(data.get("llm", CONFIG["use_llm_default"]))

        print(f"\n[ENDPOINT] /datasheet-extract-url called")
        print(f"[ENDPOINT] URL: {url} | llm: {use_llm}")

        result = run_extraction(url, use_llm=use_llm)
        print(f"[ENDPOINT] Extracted {result['fields_found']}/{result['fields_total']} fields")

        response = format_response(url, result)
        print(f"[ENDPOINT] Processing complete")
        return jsonify(response), 200

    except Exception as e:
        print(f"[ENDPOINT ERROR] {str(e)}")
        return jsonify({
            "success": False, "error": str(e),
            "timestamp": datetime.datetime.now().isoformat(),
        }), 500

def run_flask(port=5011):
    app.run(host="0.0.0.0", port=port, debug=False)

def main():
    use_ngrok = os.getenv("USE_NGROK", "false").lower() == "true"
    port = int(os.getenv("PORT", 5011))
    try:
        from IPython import get_ipython
        if "google.colab" in str(get_ipython()):
            print("[INFO] Detected Colab environment; setting up dependencies...")
            import subprocess
            subprocess.run(["pip", "install", "flask", "pyngrok"], check=True)
            use_ngrok = True
    except Exception:
        pass  # Not running in Colab

    if use_ngrok:
        auth_token = os.getenv("NGROK_AUTH_TOKEN")
        if not auth_token:
            raise ValueError(
                "NGROK_AUTH_TOKEN not set. Get one from https://dashboard.ngrok.com/get-started/your-authtoken"
            )

        ngrok.set_auth_token(auth_token)
        print(f"[INFO] Ngrok auth token set: {auth_token[:5]}... (masked)")

        try:
            public_url = ngrok.connect(addr=str(port), proto="http")
            print(f"[INFO] Public URL for testing in Postman: {public_url}")
        except Exception as e:
            print(f"[WARNING] Port {port} failed: {e}, retrying on port {port + 1}")
            port += 1
            public_url = ngrok.connect(addr=str(port), proto="http")
            print(f"[INFO] Public URL for testing in Postman: {public_url}")
        flask_thread = threading.Thread(target=run_flask, args=(port,), daemon=True)
        flask_thread.start()
        flask_thread.join()
    else:
        print(f"[INFO] Running Flask on port {port} without ngrok (production mode)")
        run_flask(port)

if __name__ == "__main__":
    try:
        from IPython import get_ipython  # For Colab detection
    except ImportError:
        get_ipython = lambda: None  # Fallback for non-Colab environments
    main()

